### ISSUE TITLE
System configuration issue 

### ISSUE THREAD

**Issue by abdullah22842** [VinAIResearch/WaveDiff#10]
Thanks' for sharing your work.

I am trying to run this code on cifar10 but it seems to be error in system configuration. I have 2 questions.

Q1. On my system the cuda  version 12.2  is already install and now i am making new environment as instruction given in read.me . It create any problem?

Q2. The environment is  successfully  created but when i try to run on cifar10, it pop-up some error like  "/.cache/torch_extensions/py37_cu102/fused/fused.so: cannot open shared object file" . How I can solve this issue?

<img width="603" alt="week4" src="https://github.com/VinAIResearch/WaveDiff/assets/52751469/2573f035-eef8-4f39-821a-d5b1cae58d3a">

**Comment by hao-pt** [comment]
Hi,

Q1. I think it is okay to use different cuda versions.
Q2. Have you looked at this [link](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s)? This error maybe due to missing paths and packages. If this does not work, you can try install cudatoolkit for conda env: `conda install -c conda-forge cudatoolkit-dev`. I am not sure whether it helps you or not 'cause I have never met this problem before.
